-- Teams
call NewTeam('AFC Bournemouth','Bournemouth','GB');
call NewTeam('Arsenal Football Club','Arsenal','GB');
call NewTeam('Burnley Football Club','Burnley','GB');
call NewTeam('Chelsea Football Club','Chelsea','GB');
call NewTeam('Crystal Palace Football Club','Crystal Palace','GB');
call NewTeam('Everton Football Club','Everton','GB');
call NewTeam('Hull City Association Football Club','Hull','GB');
call NewTeam('Leicester City Football Club','Leicester','GB');
call NewTeam('Liverpool Football Club','Liverpool','GB');
call NewTeam('Manchester City Football Club','Manchester City','GB');
call NewTeam('Manchester United Football Club','Manchester United','GB');
call NewTeam('Middlesbrough Football Club','Middlesbro','GB');
call NewTeam('Southampton Football Club','Southampton','GB');
call NewTeam('Stoke City Football Club','Stoke','GB');
call NewTeam('Sunderland Association Football Club','Sunderland','GB');
call NewTeam('Swansea City Association ','Swansea','GB');
call NewTeam('Tottenham Hotspur Football Club','Tottenham','GB');
call NewTeam('Watford Football Club','Watford','GB');
call NewTeam('West Bromwich Albion Football Club','West Bromwich Albion','GB');
call NewTeam('West Ham United Football Club','West Ham','GB');
call NewTeam('Aston Villa Football Club','Aston Villa','GB');
call NewTeam('Barnsley Football Club','Barnsley','GB');
call NewTeam('Birmingham City Football Club','Birmingham','GB');
call NewTeam('Blackburn Rovers Football Club','Blackburn','GB');
call NewTeam('Brentford Football Club','Brentford','GB');
call NewTeam('Brighton & Hove Albion Football Club','Brighton','GB');
call NewTeam('Bristol City Football Club','Bristol','GB');
call NewTeam('Burton Albion Football Club','Burton','GB');
call NewTeam('Cardiff City Football Club','Cardiff','GB');
call NewTeam('Derby County Football Club','Derby','GB');
call NewTeam('Fulham Football Club','Fulham','GB');
call NewTeam('Huddersfield Town Association Football Club','Huddersfield','GB');
call NewTeam('Ipswich Town Football Club','Ipswich','GB');
call NewTeam('Leeds United Football Club','Leeds','GB');
call NewTeam('Newcastle United Football Club','Newcastle','GB');
call NewTeam('Norwich City Football Club','Norwich','GB');
call NewTeam('Nottingham Forest Football Club','Nottingham Forest','GB');
call NewTeam('Preston North End Football Club','Preston North End','GB');
call NewTeam('Queens Park Rangers Football Club','Queens Park Rangers','GB');
call NewTeam('Reading Football Club','Reading','GB');
call NewTeam('Rotherham United Football Club','Rotherham','GB');
call NewTeam('Sheffield Wednesday Football Club','Sheffield Wednesday','GB');
call NewTeam('Wigan Athletic Football Club','Wigan','GB');
call NewTeam('Wolverhampton Wanderers Football Club','Wolverhampton Wanderers','GB');
call NewTeam('Fußball-Club Augsburg 1907 e.V.','Augsburg','DE');
call NewTeam('Bayer 04 Leverkusen Fußball GmbH','Leverkusen','DE');
call NewTeam('Fußball-Club Bayern München e.V.','Bayern München','DE');
call NewTeam('Ballspielverein Borussia 09 e.V. ','Borussia Dortmund','DE');
call NewTeam('Borussia VfL 1900 Mönchengladbach e.V.','Borussia Mönchengladbach','DE');
call NewTeam('Sportverein Darmstadt 1898 e.V.','Darmstadt','DE');
call NewTeam('Eintracht Frankfurt e.V.','Frankfurt','DE');
call NewTeam('Sport-Club Freiburg e.V.','Freiburg','DE');
call NewTeam('Hamburger Sport-Verein e.V.','Hamburger SV','DE');
call NewTeam('Hertha Berliner Sport-Club von 1892 e.V.','Hertha Berlin','DE');
call NewTeam('Turn- und Sportgemeinschaft 1899 Hoffenheim e.V.','Hoffenheim','DE');
call NewTeam('Fußball-Club Ingolstadt 04 e.V.','FC Ingolstadt','DE');
call NewTeam('1. Fußball-Club Köln 01/07 e. V.','FC Köln','DE');
call NewTeam('RasenBallsport Leipzig e.V,','RB Leipzig','DE');
call NewTeam('1. Fußball- und Sport-Verein Mainz 05 e.V.','Mainz','DE');
call NewTeam('Fußballclub Gelsenkirchen-Schalke 04 e.V.','Schalke 04','DE');
call NewTeam('Sportverein Werder Bremen von 1899 e. V.','Werder Bremen','DE');
call NewTeam('Verein für Leibesübungen Wolfsburg Fußball GmbH ','Vfl Wolfsburg','DE');
call NewTeam('Karlsruher Sport-Club Mühlburg-Phönix e. V.','Karlsruher SC','DE');